name: Builder

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build process
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Generate Changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create or Update Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Rename binary for upload
        run: |
          if [ "${{ runner.os }}" == "Linux" ]; then
            cp target/release/crypto-rs crypto-rs-linux
          elif [ "${{ runner.os }}" == "macOS" ]; then
            cp target/release/crypto-rs crypto-rs-macos
          elif [ "${{ runner.os }}" == "Windows" ]; then
            copy target\release\crypto-rs.exe crypto-rs-windows.exe
          fi
        shell: bash

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            crypto-rs-linux
            crypto-rs-macos
            crypto-rs-windows.exe
